Metrics/LineLength:
  Max: 300
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Layout/SpaceAroundOperators:
  Enabled: false

Performance/TimesMap:
  Enabled: false
  Style/GuardClause:
    Enabled: false
